# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_current_turn_index_alter_game_current_turn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]

